# LESS PILLAGERS configuration file
# .
# Author: ShaneBee - https://shanebeestudios.tk/
# Official plugin page: https://www.spigotmc.org/resources/lesspillagers.70184/
# GitHub repo: http://github.com/ShaneBeee/LessPillagers
# .
# settings.max-pillagers-per-outpost:
#   Max pillagers to spawn around each other (generally around an outpost)
# .
# settings.pillagers-check-radius:
#   Radius (in blocks), for each direction, used to count nearby pillagers
#   (Tip: Using a lower value in Y axis will return less entities to check by the plugin)

settings:
  max-pillagers-per-outpost: 16
  pillagers-check-radius:
    x: 100
    y: 10
    z: 100
